[package]
name = "04_mutability"
version = "0.1.0"
authors = ["shangfeiSF <tony20100125@126.com>"]

[[example]]
name = "0"
path = "examples/0.advanced_copy_auto.rs"

[[example]]
name = "1"
path = "examples/1.advanced_copy.rs"