[package]
name = "04_mutability"
version = "0.1.0"
authors = ["shangfeiSF <tony20100125@126.com>"]

[[example]]
name = "advanced_copy_auto"
path = "examples/advanced_copy_auto.rs"

[[example]]
name = "advanced_copy"
path = "examples/advanced_copy.rs"