[package]
name = "13_thread"
version = "0.1.0"
authors = ["shangfeiSF <tony20100125@126.com>"]

[[example]]
name = "0"
path = "examples/0.start_thread.rs"

[[example]]
name = "1"
path = "examples/1.change_data.rs"

[[example]]
name = "2"
path = "examples/2.safe_shared_mutable.rs"